// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeeklyScheduleManagement.Data;

#nullable disable

namespace WeeklyScheduleManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeeklyScheduleManagement.Models.DiaDiem", b =>
                {
                    b.Property<int>("MaDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaDiem"));

                    b.Property<string>("LoaiDiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDiaDiem");

                    b.ToTable("DiaDiems");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.LichTuan", b =>
                {
                    b.Property<int>("MaLichTuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichTuan"));

                    b.Property<string>("LyDoTuChoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChuTri")
                        .HasColumnType("int");

                    b.Property<int>("MaDiaDiem")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDangKy")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLichTuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLichTuan");

                    b.HasIndex("MaChuTri");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaNguoiDangKy");

                    b.HasIndex("MaNguoiDuyet");

                    b.ToTable("LichTuans");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaPhongBan")
                        .HasColumnType("int");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongBan"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongBan");

                    b.HasIndex("MaKhoa");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.ThanhPhanThamGia", b =>
                {
                    b.Property<int>("MaThanhPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhPhan"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLichTuan")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThanhPhan");

                    b.HasIndex("MaLichTuan");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("ThanhPhanThamGias");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTros");

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            TenVaiTro = "Manager"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            TenVaiTro = "GiaoVien"
                        });
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.LichTuan", b =>
                {
                    b.HasOne("WeeklyScheduleManagement.Models.NguoiDung", "ChuTri")
                        .WithMany("LichTuansChuTri")
                        .HasForeignKey("MaChuTri")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeeklyScheduleManagement.Models.DiaDiem", "DiaDiem")
                        .WithMany("LichTuans")
                        .HasForeignKey("MaDiaDiem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyScheduleManagement.Models.NguoiDung", "NguoiDangKy")
                        .WithMany("LichTuansDangKy")
                        .HasForeignKey("MaNguoiDangKy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WeeklyScheduleManagement.Models.NguoiDung", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("MaNguoiDuyet")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChuTri");

                    b.Navigation("DiaDiem");

                    b.Navigation("NguoiDangKy");

                    b.Navigation("NguoiDuyet");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.NguoiDung", b =>
                {
                    b.HasOne("WeeklyScheduleManagement.Models.PhongBan", "PhongBan")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaPhongBan");

                    b.HasOne("WeeklyScheduleManagement.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongBan");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.PhongBan", b =>
                {
                    b.HasOne("WeeklyScheduleManagement.Models.Khoa", "Khoa")
                        .WithMany("PhongBans")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.ThanhPhanThamGia", b =>
                {
                    b.HasOne("WeeklyScheduleManagement.Models.LichTuan", "LichTuan")
                        .WithMany("ThanhPhanThamGias")
                        .HasForeignKey("MaLichTuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeeklyScheduleManagement.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThanhPhanThamGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichTuan");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.DiaDiem", b =>
                {
                    b.Navigation("LichTuans");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.Khoa", b =>
                {
                    b.Navigation("PhongBans");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.LichTuan", b =>
                {
                    b.Navigation("ThanhPhanThamGias");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.NguoiDung", b =>
                {
                    b.Navigation("LichTuansChuTri");

                    b.Navigation("LichTuansDangKy");

                    b.Navigation("ThanhPhanThamGias");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.PhongBan", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("WeeklyScheduleManagement.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
